#!/usr/bin/env python3
"""Run mutation testing without copying generated Python bytecode caches."""

from __future__ import annotations

import fcntl
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
MUTMUT = ROOT / ".venv" / "bin" / "mutmut"
MUTANT_WORKSPACE = BACKEND / "mutants"
LOCK_PATH = BACKEND / ".mutmut-run.lock"
BYTECODE_ROOTS = (BACKEND / "app", BACKEND / "tests")
STAGING_IGNORE = shutil.ignore_patterns(
    "mutants",
    "__pycache__",
    ".pytest_cache",
    ".coverage",
    "*.pyc",
)


def purge_bytecode_caches(roots: tuple[Path, ...] = BYTECODE_ROOTS) -> int:
    """Remove only generated ``__pycache__`` trees below the supplied roots."""
    caches = {
        cache
        for root in roots
        if root.exists()
        for cache in root.rglob("__pycache__")
        if cache.is_dir() or cache.is_symlink()
    }
    for cache in sorted(caches, key=lambda path: len(path.parts), reverse=True):
        if cache.is_symlink():
            cache.unlink()
        else:
            shutil.rmtree(cache)
    return len(caches)


def reset_mutant_workspace(workspace: Path = MUTANT_WORKSPACE) -> bool:
    """Remove the generated mutmut workspace so every run starts from source."""
    if not workspace.exists() and not workspace.is_symlink():
        return False
    if workspace.is_symlink():
        workspace.unlink()
    else:
        shutil.rmtree(workspace)
    return True


def stage_backend(stage_root: Path) -> Path:
    """Copy mutation inputs outside synced folders and generated caches."""
    staged_backend = stage_root / "backend"
    shutil.copytree(BACKEND, staged_backend, ignore=STAGING_IGNORE)

    # The RLS contract test resolves the deployment fixture from the backend
    # root when pytest runs inside mutmut's nested ``mutants`` workspace.
    deployment = ROOT / "deployment"
    if deployment.is_dir():
        shutil.copytree(deployment, staged_backend / "deployment")
    return staged_backend


def publish_mutant_workspace(staged_backend: Path) -> None:
    """Publish only a complete mutation workspace for evidence export."""
    staged_workspace = staged_backend / "mutants"
    if not staged_workspace.is_dir():
        raise RuntimeError("mutmut completed without producing a mutant workspace")
    reset_mutant_workspace()
    shutil.copytree(staged_workspace, MUTANT_WORKSPACE)


def main(arguments: list[str] | None = None) -> int:
    if not MUTMUT.is_file():
        print("Missing .venv. Run: make setup", file=sys.stderr)
        return 2

    LOCK_PATH.touch(exist_ok=True)
    with LOCK_PATH.open("r+", encoding="utf-8") as lock_file:
        try:
            fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            print(
                "Another mutation run is active for this checkout; "
                "wait for it to finish before retrying.",
                file=sys.stderr,
            )
            return 2

        removed = purge_bytecode_caches()
        reset = reset_mutant_workspace()
        print(
            f"Purged {removed} generated bytecode cache "
            f"director{'y' if removed == 1 else 'ies'}; "
            f"mutant workspace {'reset' if reset else 'already absent'}."
        )

        environment = os.environ.copy()
        environment["NIGHTINGALE_DATABASE_URL"] = "sqlite://"
        environment["PYTHONDONTWRITEBYTECODE"] = "1"
        forwarded = list(arguments if arguments is not None else sys.argv[1:])
        if "--max-children" not in forwarded:
            # Four workers avoid false timeout verdicts observed under eight-way
            # contention while still keeping the complete critical run practical.
            forwarded = ["--max-children", str(min(os.cpu_count() or 2, 4)), *forwarded]

        with tempfile.TemporaryDirectory(prefix="nightingale-mutmut-") as temp_dir:
            staged_backend = stage_backend(Path(temp_dir))
            print(f"Running mutmut in local staging workspace: {staged_backend}")
            command = [str(MUTMUT), "run", *forwarded]
            result = subprocess.run(  # noqa: S603
                command,
                cwd=staged_backend,
                env=environment,
                check=False,
            )
            if result.returncode == 0:
                publish_mutant_workspace(staged_backend)
                print(f"Published complete mutation evidence to: {MUTANT_WORKSPACE}")
            return result.returncode


if __name__ == "__main__":
    raise SystemExit(main())
