#!/usr/bin/env python3
"""Run mutation testing without copying generated Python bytecode caches."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
MUTMUT = ROOT / ".venv" / "bin" / "mutmut"
MUTANT_WORKSPACE = BACKEND / "mutants"
BYTECODE_ROOTS = (BACKEND / "app", BACKEND / "tests")


def purge_bytecode_caches(roots: tuple[Path, ...] = BYTECODE_ROOTS) -> int:
    """Remove only generated ``__pycache__`` trees below the supplied roots."""
    caches = {
        cache
        for root in roots
        if root.exists()
        for cache in root.rglob("__pycache__")
        if cache.is_dir() or cache.is_symlink()
    }
    for cache in sorted(caches, key=lambda path: len(path.parts), reverse=True):
        if cache.is_symlink():
            cache.unlink()
        else:
            shutil.rmtree(cache)
    return len(caches)


def reset_mutant_workspace(workspace: Path = MUTANT_WORKSPACE) -> bool:
    """Remove the generated mutmut workspace so every run starts from source."""
    if not workspace.exists() and not workspace.is_symlink():
        return False
    if workspace.is_symlink():
        workspace.unlink()
    else:
        shutil.rmtree(workspace)
    return True


def main(arguments: list[str] | None = None) -> int:
    if not MUTMUT.is_file():
        print("Missing .venv. Run: make setup", file=sys.stderr)
        return 2

    removed = purge_bytecode_caches()
    reset = reset_mutant_workspace()
    print(
        f"Purged {removed} generated bytecode cache "
        f"director{'y' if removed == 1 else 'ies'}; "
        f"mutant workspace {'reset' if reset else 'already absent'}."
    )

    environment = os.environ.copy()
    environment["NIGHTINGALE_DATABASE_URL"] = "sqlite://"
    environment["PYTHONDONTWRITEBYTECODE"] = "1"
    command = [str(MUTMUT), "run", *(arguments if arguments is not None else sys.argv[1:])]
    return subprocess.run(command, cwd=BACKEND, env=environment, check=False).returncode  # noqa: S603


if __name__ == "__main__":
    raise SystemExit(main())
